version: 2.1
jobs:
  test:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python -m pip install --upgrade pip
            pip install pytest pytest-cov
      - run:
          name: Create test results directory
          command: mkdir -p test-results
      - run:
          name: Run tests
          command: |
            python -m pytest --junitxml=test-results/junit.xml --cov=./ --cov-report=xml:test-results/coverage.xml
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: test-results
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Build an artifact
          command: touch example.txt
      - store_artifacts:
          path: example.txt
  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: deploy
          command: '#e.g. ./deploy.sh'
workflows:
  example:
    jobs:
      - test
      - build:
          requires:
            - test
      - deploy:
          requires:
            - test
